config/routes.rb
Rails.application.routes.draw do
  resources :occupations
  devise_for :admins, controllers: {
    registrations: "admins/registrations",
    sessions: "admins/sessions"
  }
  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions"
  }
  resources :regulations
  resources :calenders
  resources :rooms
  root "rooms#index"
end

app/models/calender.rb
class Calender < ApplicationRecord
  scope :enable, -> { where('day >= ?', Date.today) }
  validates :day, presence: true, uniqueness: true
  validate :time_valid, if: :time_changed?
  validate :interval_valid, if: :interval_changed?

  def time_changed?
    self.begin_time_changed? || self.close_time_changed?
  end

  def interval_changed?
    self.interval_s_changed? || self.interval_e_changed?
  end

  def time_valid
    if self.close_time < self.begin_time
      errors.add(:close_time, "の時刻は、#{self.begin_time.strftime('%H:%M')}より前の時刻にしてください。")
      return
    end
  end

  def interval_valid
    if self.interval_e < self.interval_s
      errors.add(:interval_e, "の時刻は、#{self.interval_s.strftime('%H:%M')}より前の時刻にしてください。")
      return
    end

    if self.interval_e > self.close_time
      errors.add(:interval_e, "の時刻は、#{self.close_time.strftime('%H:%M')}より前の時刻にしてください。")
      return
    end

    if self.interval_s < self.begin_time
      errors.add(:interval_s, "の時刻は、#{self.begin_time.strftime('%H:%M')}より後の時刻にしてください。")
      return
    end
  end
end

app/controllers/calenders_controller.rb
class CalendersController < ApplicationController
  before_action :set_calender, only: %i[ show edit update destroy ]
  include CalenderData

  # GET /calenders or /calenders.json
  def index
    @calenders = Calender.all
    month = params[:month]
    calender_for_view(month)

    regulation = Regulation.last
    @begin_time = regulation.begin_time
    @close_time = regulation.close_time
    @interval_s = regulation.interval_s
    @interval_e = regulation.interval_e
    @unit_minute = regulation.unit_minute
  end

  # GET /calenders/1 or /calenders/1.json
  def show
  end

  # GET /calenders/new
  def new
    @calender = Calender.new
    @calender.day = params[:day]
    puts params[:begin_time]
    @calender.begin_time = params[:day] + 'T' + params[:begin_time]
    @calender.close_time = params[:day] + 'T' + params[:close_time]
    @calender.interval_s = params[:day] + 'T' + params[:interval_s]
    @calender.interval_e = params[:day] + 'T' + params[:interval_e]
    @calender.unit_minute = params[:unit_minute]
  end

  # GET /calenders/1/edit
  def edit
  end

  # POST /calenders or /calenders.json
  def create
    @calender = Calender.new(calender_params)

    respond_to do |format|
      if @calender.save
        format.html { redirect_to calender_url(@calender), notice: "Calender was successfully created." }
        format.json { render :show, status: :created, location: @calender }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @calender.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /calenders/1 or /calenders/1.json
  def update
    respond_to do |format|
      if @calender.update(calender_params)
        format.html { redirect_to calender_url(@calender), notice: "Calender was successfully updated." }
        format.json { render :show, status: :ok, location: @calender }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @calender.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /calenders/1 or /calenders/1.json
  def destroy
    @calender.destroy!

    respond_to do |format|
      format.html { redirect_to calenders_url, notice: "Calender was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_calender
      @calender = Calender.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def calender_params
      params.require(:calender).permit(:day, :begin_time, :close_time, :interval_s, :interval_e, :unit_minute, :no_use)
    end
end

app/helpers/calenders_helper.rb
module CalendersHelper
end

app/views/calenders/_calender.html.erb
<div id="<%= dom_id calender %>">
  <p>
    <strong>Day:</strong>
    <%= calender.day %>
  </p>

  <p>
    <strong>Begin time:</strong>
    <%= calender.begin_time %>
  </p>

  <p>
    <strong>Close time:</strong>
    <%= calender.close_time %>
  </p>

  <p>
    <strong>Interval s:</strong>
    <%= calender.interval_s %>
  </p>

  <p>
    <strong>Interval e:</strong>
    <%= calender.interval_e %>
  </p>

  <p>
    <strong>Unit minute:</strong>
    <%= calender.unit_minute %>
  </p>

  <p>
    <strong>No use:</strong>
    <%= calender.no_use %>
  </p>

</div>

app/views/calenders/_form.html.erb
<%= form_with(model: calender) do |form| %>
  <% if calender.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(calender.errors.count, "error") %> prohibited this calender from being saved:</h2>

      <ul>
        <% calender.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.hidden_field :day %>

  <div class="my-5">
    <%= form.label :day %>
    <% if action_name == 'new' %>
      <%= form.date_field :day, \
          class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
    <% else %>
      <% wd = ['日', '月', '火', '水', '木', '金', '土'] %>
      <%= content_tag(:div, calender.day.strftime("%Y年%m月%d日 (#{wd[calender.day.wday]})"), \
                      class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full") %>
    <% end %>
  </div>

  <div class="my-5">
    <%= form.label :begin_time %>
    <%= form.datetime_field :begin_time, \
        class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :close_time %>
    <%= form.datetime_field :close_time, \
        class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :interval_s %>
    <%= form.datetime_field :interval_s, \
        class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :interval_e %>
    <%= form.datetime_field :interval_e, \
        class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :unit_minute %>
    <%= form.number_field :unit_minute, \
        class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :no_use %>
    <%= form.check_box :no_use, class: "block mt-2 h-5 w-5" %>
  </div>

  <div class="inline">
    <%= form.submit \
        class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/calenders/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">カレンダー編集</h1>

  <%= render "form", calender: @calender %>

  <%= link_to "戻る", calenders_path, \
      class: "ml-2 rounded-lg py-3 px-5 inline-block font-medium bg-gray-100" %>
</div>

app/views/calenders/index.html.erb
<div class="w-full">

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Calender日付管理</h1>
  </div>

  <div class="wrapper bg-white rounded shadow w-full my-10">
    <!-- タイトル見出しここから -->
    <div class="header flex justify-between border-b p-2">
      <span class="text-lg font-bold">
        <%= @today.strftime("%Y年 %m月") %>
      </span>
      <% nextmonth = (@today == Date.today) ? false : true %>
      <div class="buttons">
        <% if nextmonth %>
          <%= link_to(calenders_path(month: "prev"), class: "p-1") do %>
            <i class="text-green-300">←</i>
          <% end %>
          <i class="text-gray-300">→</i>
        <% else %>
          <i class="text-gray-300">←</i>
          <%= link_to(calenders_path(month: "next"), class: "p-1") do %>
            <i class="text-green-300">→</i>
          <% end %>
        <% end %>
      </div>
    </div>
    <!-- タイトル見出しここまで -->

    <table class="w-full">
      <thead>
        <tr>
          <th class="p-2 border-r h-10 xl:w-40 lg:w-30 md:w-30 sm:w-20 w-10 xl:text-sm text-xs">
            <span class="block">日</span>
          </th>
          <th class="p-2 border-r h-10 xl:w-40 lg:w-30 md:w-30 sm:w-20 w-10 xl:text-sm text-xs">
            <span class="block">月</span>
          </th>
          <th class="p-2 border-r h-10 xl:w-40 lg:w-30 md:w-30 sm:w-20 w-10 xl:text-sm text-xs">
            <span class="block">火</span>
          </th>
          <th class="p-2 border-r h-10 xl:w-40 lg:w-30 md:w-30 sm:w-20 w-10 xl:text-sm text-xs">
            <span class="block">水</span>
          </th>
          <th class="p-2 border-r h-10 xl:w-40 lg:w-30 md:w-30 sm:w-20 w-10 xl:text-sm text-xs">
            <span class="block">木</span>
          </th>
          <th class="p-2 border-r h-10 xl:w-40 lg:w-30 md:w-30 sm:w-20 w-10 xl:text-sm text-xs">
            <span class="block">金</span>
          </th>
          <th class="p-2 border-r h-10 xl:w-40 lg:w-30 md:w-30 sm:w-20 w-10 xl:text-sm text-xs">
            <span class="block">土</span>
          </th>
        </tr>
      </thead>
      <tbody>
      <% @weeks.each do |wk| %>
        <tr class="text-center h-20">
        <% wk.each do |day| %>
          <% this_month = (day.strftime("%m") == @this_month) ? true : false %>
          <% is_close    = (@day_enable[day] == :closed) ? true : false %>

          <td class="border <%= this_month ? '' : 'bg-gray-100' %> p-1 h-40 xl:w-40 lg:w-30 md:w-30 sm:w-20 w-10 overflow-auto transition  duration-500 ease hover:bg-gray-300">
            <div class="flex flex-col h-40 mx-auto xl:w-40 lg:w-30 md:w-30 sm:w-full w-10 overflow-hidden">
              <div class="top h-5 w-full">
                <span class="text-gray-500"><%= day.strftime("%e") %></span>
              </div>
              <div class="bottom flex-grow h-30 py-1 w-full">
                <div class="<%= is_close ? 'bg-purple-200' : 'bg-blue-400' %> text-white rounded p-1 text-sm mb-1">
                  <span class="event-name">
                    <%= @day_enable[day] %>
                  </span>
                </div>
                <% params = {day: day, begin_time: @begin_time, close_time: @close_time, interval_s: @interval_s, interval_e: @interval_e, unit_minute: @unit_minute} %>
                <%= link_to '稼働日作成', new_calender_path(params), 
                    class: "rounded-lg py-3 px-5 bg-blue-300 text-white block font-medium" \
                    if day >= Date.today && is_close %>
              </div>
            </div>
          </td>
        <% end %>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>

  <table class="table-auto mb-10">
    <thead>
      <tr>
        <th class="px-4 py-2">日付</th>
        <th class="px-4 py-2">開始</th>
        <th class="px-4 py-2">終了</th>
        <th class="px-4 py-2">昼休開始</th>
        <th class="px-4 py-2">昼休終了</th>
        <th class="px-4 py-2">単位：分</th>
        <th class="px-4 py-2">休み</th>
        <th class="px-4 py-2"></th>
        <th class="px-4 py-2"></th>
      </tr>
    </thead>
    <tbody>
      <% @calenders.each do |cal| %>
        <% if cal.day >= @today %>
          <tr>
            <td class="border px-4 py-2"><%= cal.day %></td>
            <td class="border px-4 py-2"><%= cal.begin_time.strftime("%R") %></td>
            <td class="border px-4 py-2"><%= cal.close_time.strftime("%R") %></td>
            <td class="border px-4 py-2"><%= cal.interval_s.strftime("%R") %></td>
            <td class="border px-4 py-2"><%= cal.interval_e.strftime("%R") %></td>
            <td class="border px-4 py-2"><%= cal.unit_minute %></td>
            <td class="border px-4 py-2"><%= cal.no_use %></td>
            <td class="border px-4 py-2"><%= link_to '編集', edit_calender_path(cal), class: "frm_btn bg-gray-400" %></td>
            <td class="border px-4 py-2"><%= button_to '削除', calender_path(cal), method: :delete, class: "frm_btn bg-red-400" %></td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>

</div>

app/views/calenders/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">カレンダー新規登録</h1>

  <%= render "form", calender: @calender %>

  <%= link_to '戻る', calenders_path, \
      class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/calenders/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @calender %>

    <%= link_to 'Edit this calender', edit_calender_path(@calender), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this calender', calender_path(@calender), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to calenders', calenders_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>