config/routes.rb
Rails.application.routes.draw do
  resources :occupations
  devise_for :admins, controllers: {
    registrations: "admins/registrations",
    sessions: "admins/sessions"
  }
  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions"
  }
  resources :regulations
  resources :calenders
  resources :rooms
  root "rooms#index"
end

app/models/regulation.rb
class Regulation < ApplicationRecord
end

app/controllers/regulations_controller.rb
class RegulationsController < ApplicationController
  before_action :set_regulation, only: %i[ show edit update destroy ]

  # GET /regulations or /regulations.json
  def index
    @regulation = Regulation.last
  end

  # GET /regulations/1 or /regulations/1.json
  def show
  end

  # GET /regulations/new
  def new
    @regulation = Regulation.new
  end

  # GET /regulations/1/edit
  def edit
  end

  # POST /regulations or /regulations.json
  def create
    @regulation = Regulation.new(regulation_params)

    respond_to do |format|
      if @regulation.save
        format.html { redirect_to regulation_url(@regulation), notice: "Regulation was successfully created." }
        format.json { render :show, status: :created, location: @regulation }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @regulation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /regulations/1 or /regulations/1.json
  def update
    respond_to do |format|
      if @regulation.update(regulation_params)
        format.html { redirect_to regulation_url(@regulation), notice: "Regulation was successfully updated." }
        format.json { render :show, status: :ok, location: @regulation }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @regulation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /regulations/1 or /regulations/1.json
  def destroy
    @regulation.destroy!

    respond_to do |format|
      format.html { redirect_to regulations_url, notice: "Regulation was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_regulation
      @regulation = Regulation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def regulation_params
      params.require(:regulation).permit(:begin_time, :close_time, :interval_s, :interval_e, :unit_minute, :version)
    end
end

app/helpers/regulations_helper.rb
module RegulationsHelper
end

app/views/regulations/_form.html.erb
<%= form_with(model: regulation, class: "contents") do |form| %>
  <% if regulation.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(regulation.errors.count, "error") %> prohibited this regulation from being saved:</h2>

      <ul>
        <% regulation.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :begin_time %>
    <%= form.select :begin_time, ["08:00", "08:30", "09:00", "09:30", "10:00" ], {}, \
        class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :close_time %>
    <%= form.select :close_time, ["16:00", "16:30", "17:00", "17:30", "18:00" ], {}, \
        class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :interval_s %>
    <%= form.select :interval_s, ["11:00", "11:30", "12:00", "12:30", "13:00" ], {}, \
        class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :interval_e %>
    <%= form.select :interval_e, ["12:00", "12:30", "13:00", "13:30", "14:00" ], {}, \
        class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :unit_minute %>
    <%= form.select :unit_minute, [15, 30, 60], {}, \
        class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :version %>
    <%= form.text_field :version, \
        class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 text-white inline-block font-medium cursor-pointer bg-blue-600" %>
  </div>
<% end %>

app/views/regulations/_regulation.html.erb
<div id="<%= dom_id regulation %>">
  <p>
    <strong>Begin time:</strong>
    <%= regulation.begin_time %>
  </p>

  <p>
    <strong>Close time:</strong>
    <%= regulation.close_time %>
  </p>

  <p>
    <strong>Interval s:</strong>
    <%= regulation.interval_s %>
  </p>

  <p>
    <strong>Interval e:</strong>
    <%= regulation.interval_e %>
  </p>

  <p>
    <strong>Unit minute:</strong>
    <%= regulation.unit_minute %>
  </p>

  <p>
    <strong>Version:</strong>
    <%= regulation.version %>
  </p>

</div>

app/views/regulations/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">新規 就業規則</h1>

  <%= render "form", regulation: @regulation %>

  <%= link_to "戻る", regulations_path, \
      class: "ml-2 rounded-lg py-3 px-5 inline-block font-medium bg-gray-100" %>
</div>

app/views/regulations/index.html.erb
<div class="w-full">
  <table class="table-auto">
    <caption class="text-2xl font-bold pb-4">就業規則</caption>
    <thead>
      <tr>
        <th class="px-4 py-2">始業時刻</th>
        <th class="px-4 py-2">終業時刻</th>
        <th class="px-4 py-2">昼休開始</th>
        <th class="px-4 py-2">昼休終了</th>
        <th class="px-4 py-2">単位：分</th>
        <th class="px-4 py-2">バージョン</th>
        <th class="px-4 py-2"></th>
        <th class="px-4 py-2"></th>
        <th class="px-4 py-2"></th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td class="border px-4 py-2"><%= @regulation.begin_time if @regulation %></td>
        <td class="border px-4 py-2"><%= @regulation.close_time if @regulation %></td>
        <td class="border px-4 py-2"><%= @regulation.interval_s if @regulation %></td>
        <td class="border px-4 py-2"><%= @regulation.interval_e if @regulation %></td>
        <td class="border px-4 py-2"><%= @regulation.unit_minute if @regulation %></td>
        <td class="border px-4 py-2"><%= @regulation.version if @regulation %></td>
        <td class="border px-4 py-2">
          <%= link_to '新規作成', new_regulation_path, \
              class: 'rounded-lg py-3 px-5 text-white inline-block font-medium cursor-pointer bg-blue-400' %>
        </td>
        <td class="border px-4 py-2">
          <%= link_to '変更', edit_calender_path(@regulation), \
              class: 'rounded-lg py-3 px-5 text-white inline-block font-medium cursor-pointer bg-green-400' \
              if @regulation %>
        </td>
      </tr>
    </tbody>
  </table>
</div>

app/views/regulations/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">新規 就業規則</h1>

  <%= render "form", regulation: @regulation %>

  <%= link_to '戻る', regulations_path, \
      class: "ml-2 rounded-lg py-3 px-5 inline-block font-medium bg-gray-100" %>
</div>

app/views/regulations/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">

    <%= render @regulation %>

    <%= link_to '編集', edit_regulation_path(@regulation), \
        class: "mt-2 rounded-lg py-3 px-5 inline-block font-medium bg-gray-100" %>
    <div class="inline-block ml-2">
      <%= button_to '削除', regulation_path(@regulation), method: :delete, \
          class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to '戻る', regulations_path, \
        class: "ml-2 rounded-lg py-3 px-5 inline-block font-medium bg-gray-100" %>
  </div>
</div>