config/routes.rb
Rails.application.routes.draw do
  resources :occupations
  devise_for :admins, controllers: {
    registrations: "admins/registrations",
    sessions: "admins/sessions"
  }
  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions"
  }
  resources :regulations
  resources :calenders
  resources :rooms
  root "rooms#index"
end

app/views/layouts/_navi.html.erb
<nav class="bg-purple-900 text-white flex justify-between">
  <img src="" class="h-14 rounded-full px-0" alt="">
  <ul class="px-10 py-4 flex space-x-3 ">
    <%= content_tag(:li, class: "cursor-pointer") do
        link_to("HOME", root_path) end if !admin_signed_in? %>

    <%= content_tag(:li, class: "cursor-pointer") do
        link_to("ルーム", rooms_path) end if admin_signed_in? %>

    <%= content_tag(:li, class: "cursor-pointer") do
        link_to("予約", occupations_path) end if user_signed_in? %>

    <%= content_tag(:li, class: "cursor-pointer") do
        link_to("就業規則", regulations_path) end if admin_signed_in? %>

    <%= content_tag(:li, class: "cursor-pointer") do
        link_to("カレンダー", calenders_path) end if admin_signed_in? %>

    <%= content_tag(:li, class: "cursor-pointer") do
        link_to("登録", new_user_registration_path) end \
        if !user_signed_in? && !admin_signed_in? %>

    <%= content_tag(:li, class: "cursor-pointer") do
        link_to("ログイン", new_user_session_path) end \
        if !user_signed_in? && !admin_signed_in? %>

    <%= content_tag(:li, class: "cursor-pointer") do
        link_to("ADMINログイン", new_admin_session_path) end \
        if !user_signed_in? && !admin_signed_in? %>

    <%= content_tag(:li, class: "cursor-pointer") do
        link_to("ログアウト", destroy_user_session_path,
        data: { turbo_method: :delete }) end \
        if user_signed_in? %>

    <%= content_tag(:li, class: "cursor-pointer") do
        link_to("ADMINログアウト", destroy_user_session_path,
        data: { turbo_method: :delete }) end \
        if admin_signed_in? %>

    <%= content_tag(:li, class: "cursor-pointer") do
        link_to("ADMIN登録", new_admin_registration_path) end \
        if !user_signed_in? && !admin_signed_in? %>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rvue</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://cdn.tailwindcss.com"></script>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= yield(:meta_t) %>
  </head>

  <body>
    <%= render 'layouts/navi' %>
    <div class="container mx-auto mt-6 px-5">
      <% if notice.present? %>
        <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
      <% end %>
      <% if alert.present? %>
         <p class="py-2 px-3 bg-green-50 mb-5 text-pink-500 font-medium rounded-lg inline-block" id="alert"><%= alert %></p>
      <% end %>
    </div>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>